apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-reconcile
  labels:
    app.kubernetes.io/name: hello-reconcile
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-reconcile
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-reconcile
    spec:
      containers:
        - name: podinfo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
          envFrom:
            - configMapRef:
                name: hello-reconcile
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
