#!/usr/bin/env bash
# Prepare an isolated two-resource exercise; all meaningful fix steps stay in the guide.
set -euo pipefail
PACKAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_FILE="$PACKAGE_DIR/run.env"
fail() { printf '%s\n' "$*" >&2; exit 1; }
for tool in git kubectl argocd; do
  command -v "$tool" >/dev/null || fail "Missing command: $tool"
done

case "${1:-}" in
prepare)
  if [ -f "$STATE_FILE" ]; then
    printf 'A practice run is already recorded. Continue with: source run.env\nTo start fresh, first run: bash practice.sh cleanup\n'
    exit 0
  fi
  # Use the existing checkout only to discover the Mac/VM-accessible Git URL and identity.
  SOURCE_REPO="${SOURCE_REPO:-$HOME/hello-reconcile}"
  git -C "$SOURCE_REPO" rev-parse --git-dir >/dev/null 2>&1 || fail "Cannot find checkout: $SOURCE_REPO"
  CLIENT_REPO_URL="$(git -C "$SOURCE_REPO" remote get-url origin)"
  ARGO_REPO_URL="${ARGO_REPO_URL:-http://lab-gitea:3000/course/hello-reconcile.git}"
  kubectl --context k3d-mgmt -n argocd get application hello-reconcile >/dev/null
  argocd app list >/dev/null
  # A fresh clone avoids altering or rebasing the existing local main branch.
  RUN_DIR="$(mktemp -d "$HOME/argo-waves.XXXXXX")"
  RUN_SUFFIX="${RUN_DIR##*.}"
  RUN_SUFFIX="$(printf '%s' "$RUN_SUFFIX" | tr '[:upper:]' '[:lower:]')"
  APP="waves-$RUN_SUFFIX"
  NS="$APP"
  BRANCH="$APP"
  WORKTREE="$RUN_DIR/repo"
  # Save state before remote mutations so even a partial prepare can be cleaned up.
  {
    printf 'APP=%q\n' "$APP"
    printf 'NS=%q\n' "$NS"
    printf 'BRANCH=%q\n' "$BRANCH"
    printf 'WORKTREE=%q\n' "$WORKTREE"
    printf 'PACKAGE_DIR=%q\n' "$PACKAGE_DIR"
  } > "$STATE_FILE"
  git clone --branch main --single-branch "$CLIENT_REPO_URL" "$WORKTREE"
  AUTHOR_NAME="$(git -C "$SOURCE_REPO" config user.name || true)"
  AUTHOR_EMAIL="$(git -C "$SOURCE_REPO" config user.email || true)"
  git -C "$WORKTREE" config user.name "${AUTHOR_NAME:-Lab User}"
  git -C "$WORKTREE" config user.email "${AUTHOR_EMAIL:-student@lab.local}"
  git -C "$WORKTREE" switch -c "$BRANCH"
  # Unique folder avoids inheriting exercise files from any previous run.
  mkdir "$WORKTREE/$APP"
  cp "$PACKAGE_DIR/manifests/job.yaml" "$PACKAGE_DIR/manifests/settings.yaml" "$WORKTREE/$APP/"
  git -C "$WORKTREE" add "$APP"
  git -C "$WORKTREE" commit -m "Prepare isolated sync-wave dependency exercise"
  git -C "$WORKTREE" push -u origin "$BRANCH"
  argocd app create "$APP" \
    --repo "$ARGO_REPO_URL" --path "$APP" --revision "$BRANCH" \
    --dest-server https://kubernetes.default.svc --dest-namespace "$NS" \
    --sync-option CreateNamespace=true --sync-policy none
  printf '\nReady. Application: %s\nNext: source run.env\n' "$APP"
  ;;
cleanup)
  [ -f "$STATE_FILE" ] || fail "No run.env exists; no practice run to clean up."
  source "$STATE_FILE"
  # Limit deletion to names generated by this exercise.
  [[ "$APP" =~ ^waves-[a-z0-9]+$ ]] || fail "Unexpected Application name in run.env"
  [ "$NS" = "$APP" ] || fail "Namespace does not match the recorded practice Application"
  FOUND="$(kubectl --context k3d-mgmt -n argocd get application "$APP" --ignore-not-found -o name)"
  if [ -n "$FOUND" ]; then
    argocd app terminate-op "$APP" || true
    argocd app delete "$APP" --yes
    kubectl --context k3d-mgmt -n argocd wait --for=delete "application/$APP" --timeout=120s
  fi
  kubectl --context k3d-mgmt delete namespace "$NS" --ignore-not-found --wait=true --timeout=120s
  mv "$STATE_FILE" "$PACKAGE_DIR/completed-$APP.env"
  printf 'Practice Application and namespace removed.\nGit branch %s and checkout %s retained for your notes.\n' "$BRANCH" "$WORKTREE"
  ;;
*) fail "Usage: bash practice.sh prepare | cleanup" ;;
esac
